version: 2.1

jobs:
  build_doc:
    docker:
      - image: circleci/python:3.6

    steps:
      - checkout
      - run:
          name: Install Java
          command: |
            sudo apt-get update
            sudo apt-get install default-jdk -y
            sudo apt-get install maven -y
            java -version
      - run:
          name: Install Python dependencies
          command: |
            pip --version
            pip install --progress-bar off . \
              -r ./dev/large-requirements.txt \
              sphinx sphinx-click
      - run:
          name: Build documentation
          working_directory: docs
          environment:
            JAVA_HOME: /usr/lib/jvm/default-java
          command: |
            make rsthtml
            make javadocs
      - store_artifacts:
          path: docs/build/html

workflows:
  build:
    jobs:
      - build_doc
